################################################################################
# Dockerfile that builds 'yanwk/sd-webui-base:magma'.
# Complie-install magma. 
# This takes 20~30min on a Ryzen 1700 8-Core CPU to build.
################################################################################

FROM yanwk/sd-webui-base:dev-env

LABEL maintainer="code@yanwk.fun"

WORKDIR /root

# Magma for PyTorch2
# https://bitbucket.org/icl/magma/raw/master/README
RUN cd /root \
    && source /opt/intel/oneapi/setvars.sh intel64 \
    && git clone --depth=1 https://bitbucket.org/icl/magma.git \
    && cd magma \
    && cp -f make.inc-examples/make.inc.mkl-icc-ilp64 make.inc \
    && sed -i 's/^#GPU_TARGET.*/GPU_TARGET=sm_60 sm_61 sm_62 sm_70 sm_72 sm_75 sm_80 sm_86 sm_87 sm_89 sm_90 sm_90a/' make.inc \
    && sed -i 's/^CC\s*=\s*icc$/CC=icx/' make.inc \
    && sed -i 's/^CXX\s*=\s*icpc$/CXX=icpx/' make.inc \
    && sed -i 's/^#CUDADIR.*/CUDADIR=\/usr\/local\/cuda/' make.inc \
    && sed -i 's/^#MKLROOT.*/MKLROOT=\/opt\/intel\/oneapi\/mkl\/latest/' make.inc \
    && make generate \
    && mkdir build \
    && cd build \
    && cmake .. -G Ninja \
    && ninja \
    && ninja install

# GPU_TARGET in codename format
# GPU_TARGET=Pascal Volta Turing Ampere Hopper

# Other compile tools reference
# 1. Using cmake
# (-j for parallel)
# && make generate \
# && mkdir build \
# && cd build \
# && cmake .. \
# && cmake --build . -j \
# && cmake install

# 2. Using make
# Don't need 'make generate'
# (-j for parallel, -j17 runs 17 jobs)
# && make -j \
# && make install prefix=/usr/local/magma
 