################################################################################
# Dockerfile that builds 'yanwk/sd-webui-base:cuda-devel'.
# A environment with CUDA devkit & Intel MKL
# that can be used for compiling PyTorch2 (w/ Magma) & xFormers.
# This image would be large, and less update is needed.
################################################################################
FROM opensuse/tumbleweed:latest

LABEL maintainer="code@yanwk.fun"

WORKDIR /root

# https://gitlab.com/nvidia/container-images/cuda/
# https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl-download.html
RUN --mount=type=cache,target=/var/cache/zypp \
    set -eu \
    && printf "\
[cuda-opensuse15-x86_64]\n\
name=cuda-opensuse15-x86_64\n\
baseurl=https://developer.download.nvidia.com/compute/cuda/repos/opensuse15/x86_64\n\
enabled=1\n\
gpgcheck=1\n\
gpgkey=https://developer.download.nvidia.com/compute/cuda/repos/opensuse15/x86_64/D42D0685.pub\n" \
        > /etc/zypp/repos.d/cuda-opensuse15.repo \
    && printf "\
[intel-oneapi]\n\
name=intel-oneapi\n\
baseurl=https://yum.repos.intel.com/oneapi\n\
enabled=1\n\
gpgcheck=1\n\
gpgkey=https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB\n" \
        > /etc/zypp/repos.d/intel-oneapi.repo \
    && zypper --gpg-auto-import-keys \
        install --no-confirm --no-recommends --auto-agree-with-licenses \
            git make cmake python311 python311-pip python311-devel \
            intel-oneapi-compiler-dpcpp-cpp intel-oneapi-compiler-fortran \
            intel-oneapi-mkl intel-oneapi-mkl-devel \
            cuda-cudart-12-1 cuda-compat-12-1 \
            cuda-libraries-12-1 cuda-nvtx-12-1 libnpp-12-1 libcublas-12-1 \
            cuda-command-line-tools-12-1 cuda-libraries-devel-12-1 \
            cuda-minimal-build-12-1 cuda-cudart-devel-12-1 cuda-nvprof-12-1 \
            cuda-nvml-devel-12-1 libcublas-devel-12-1 libnpp-devel-12-1 \
            cuda-nvcc-12-1 cuda-nvrtc-devel-12-1 

# Need to set environment variables after installation
# Note: 'icc' is replaced by 'icx', 'icpc' is replaced by 'icpx'
# https://www.intel.com/content/www/us/en/develop/documentation/get-started-with-dpcpp-compiler/top/get-started-on-linux.html
RUN source /opt/intel/oneapi/setvars.sh intel64 \
    && ln -s /usr/bin/python3.11 /usr/bin/python \
    && ln -s /usr/bin/python3.11 /usr/bin/python3 \
    && ln -s /usr/bin/python3.11-config /usr/bin/python3-config \
    && ln -s /usr/bin/pydoc3.11 /usr/bin/pydoc3

# PATH for NVCC
ENV PATH="${PATH}:/usr/local/cuda-12.1/bin"
ENV LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/local/cuda-12.1/lib64"
