################################################################################
# Dockerfile that builds 'yanwk/sd-webui-base:xformers'.
# A environment for compiling latest xFormers.
################################################################################

FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04 AS stage-1

WORKDIR /root

RUN --mount=type=cache,target=/var/cache/apt \
    set -eu \
    && mkdir -p /root/wheels \
    && apt update && apt upgrade -y && apt install -y \
        python3.10 python3.10-dev python3-pip python-is-python3 \
        git libgoogle-perftools-dev

# Use TCMALLOC from gperftools.
ENV LD_PRELOAD=libtcmalloc.so

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install ninja wheel setuptools numpy \
    && pip install --pre torch torchvision --force-reinstall \
        --index-url https://download.pytorch.org/whl/nightly/cu118 

# Compile xformers
# If only targets "6.1", it takes ~5min to build, on a 8-Core (Ryzen 1700) CPU.
# https://github.com/facebookresearch/xformers/blob/main/README.md#install-troubleshooting
# https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/
RUN --mount=type=cache,target=/root/.cache/pip \
    cd /root \
    && git clone --depth=1 --recurse-submodules --shallow-submodules \
        https://github.com/facebookresearch/xformers.git \
    && cd xformers \
    && pip install -r requirements.txt 

ENV TORCH_CUDA_ARCH_LIST="6.1;7.5;8.0;8.6"

RUN --mount=type=cache,target=/root/xformers/build \
    --mount=type=cache,target=/root/xformers/dist \
    cd /root/xformers \
    && python setup.py develop \
    && python setup.py bdist_wheel -d /root/wheels

# Save the result
FROM alpine:latest AS stage-final

COPY --from=stage-1 /root/wheels /wheels
