name: Publish 'xformers' to Docker Hub

on: 
  workflow_dispatch: # Can be manually triggered
#  schedule: # Runs on every Sunday, 09:00 UTC
#    - cron: '0 9 * * 0'

jobs:

  build-publish-xformers:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build disk space
        uses: easimon/maximize-build-space@master
        with:
          overprovision-lvm: 'true'
          remove-android: 'true'
      - 
        name: Git checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      -
        name: Build and push 'xformers'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile-xformers
          # Build slowly but do not crash on GitHub CI.
          build-args: |
            MAX_JOBS=2
          tags: yanwk/comfyui-boot:xformers
          push: true
