name: Publish to Docker Hub

on:
  workflow_dispatch: # trigger manually
  push:
    branches: [ main ]
    paths-ignore:
      - 'docker-compose*.yml'
      - 'README*'
      - 'docs/**'
      - 'storage/**'
      - 'nightly/**'
      - '.github/**'
      - '!.github/workflows/on-push.yml'

jobs:

  build-publish:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: yanwk/sd-webui-base:latest
